### ISSUE TITLE
Does SecondPart throw any errors(after last commit)?

### ISSUE THREAD

**Issue by EasyDevCpp** [EasyDevCpp/SoftwareChallange#11]
Manuel könntest du das bitte mal testen wenn due Zeit hast? 

commit id: 00f7785745197c20ba5755b22a1e8a6b1b455325

**Comment by manuel3108** [comment]
`p.getLastNonSkipAction() !instanceof ExchangeCarrots`
`!p.getLastNonSkipAction() instanceof ExchangeCarrots`

beides mit Java 8 nicht kompilierfähig

**Comment by EasyDevCpp** [comment]
Ja wenn muss das Ausrufezeichen vor das instanceof... Syntax von Stack Exchange sollte eigentlich gehen

**Comment by manuel3108** [comment]
Sorry für den letzten Push, den hatte ich nicht auf der Kappe. Ist jetzt behoben: https://stackoverflow.com/questions/9068150/best-way-to-negate-an-instanceof

commit: 42d5756c54823f3d4c888906447d0abdf1017d7f
