### ISSUE TITLE
Secondpart stürtzt ab

### ISSUE THREAD

**Issue by manuel3108** [EasyDevCpp/SoftwareChallange#23]
Ausprobieren und Compilieren ist immer sinnvoll. Stürtzt bei mindestens 9/10 ab

**Comment by EasyDevCpp** [comment]
Closed siehe #24

**Comment by EasyDevCpp** [comment]
Informationen wären auch sinnvoll (at) Manuel...

**Comment by manuel3108** [comment]
@EasyDevCpp: Hast du mal probiert es auszuführen? Bei mir werden dort andauernd Fehler geworfen. Wenn du es kompiliert und probiert hast und wirklich keine Fehler kommen, dann kann ich auch gerne meine Fehler melden, falls sie bei dir nicht auftreten.

Die GUI gibts hier: http://www.software-challenge.de/downloads/
Einen Texteditor hier: https://atom.io/
Und Java hier: https://wiki.ubuntuusers.de/Java_9/#Java-9-JRE

Sorry, dass das jetzt etwas genervt klingt, aber ich habe keine Lust allen Fehlern hinterherzurennen

**Comment by EasyDevCpp** [comment]
Ne aber wieso muss ich das? Wenn ich die Fehler kenne kann ich sie korrigieren ohne zu testen außerdem antworten bitte an #24 weil der fehler definitiv in der GetMostEfficicientAction() liegt
