### ISSUE TITLE
GetMostEfficicientAction() does not work properly

### ISSUE THREAD

**Issue by EasyDevCpp** [EasyDevCpp/SoftwareChallange#24]
Offenkundig funktioniert die Methode nir teilweise...

Verbunden mit: #14

**Comment by manuel3108** [comment]
[24-1.zip](https://github.com/EasyDevCpp/SoftwareChallenge/files/1585687/24-1.zip)
[24-2.zip](https://github.com/EasyDevCpp/SoftwareChallenge/files/1585688/24-2.zip)

Hier zum Beispiel mal zwei Fehler. Ich habe es einfach mal ausgeführt und habe diese beiden Fehler bei den ersten beiden Spielstarts bekommen. In den Dateien sind alle Daten, die ich bekommen kann, und jetzt kennst du den Fehler, und kannst ihn beheben ohne ihn zu testen: Du kennst ihn ja schließlich :)

**Comment by EasyDevCpp** [comment]
Ich werde das Gefühl nicht los das getPossibleMoves() einfach nicht das macht was es soll oder das der gamestate zu spät bzw. gar nicht geupdated wird... Bin mir aber nicht sicher aber mein code ost ansich fehler frei... Werde im ICE das ganze mal genauer analysieren vielleicht kann ich ja das Problem beheben ansonsten liegt der Fehler in Kiel und nicht bei mir

**Comment by manuel3108** [comment]
Dein Code an sich ist wahrschienlich schon fehlerfrei, ich kann mir aber nicht vorstellen, dass der Gamestate zu spät gesetzt wird. Was meinst du mit ICE? Ich könnt mir vorstellen, dass wir einfahc einen Entscheidenenden Besatndteil vergessen haben. Ich schaue mir das gleich noch einmal genauer an

**Comment by manuel3108** [comment]
Ich denke ich habe den Denk-Fehler gefunden. Wir kriegen ja von Kiel possibleMoves (also Klasse Move). Diese Move Klasse kann ja mehrere Actions beinhalten ausführen. Das Problem bei dem was wir in der Sigmoid Klasse machen, ist, dass wir uns die Moves gar nicht ansehen, sondern nur auf die einzelnen Actions achten, weobei wir wissen, dass ein Move aus mehreren Actions bestehen kann.

Deshalb sollte man meiner Meinung für jeden einzelnen Move die Sigmoid geschichte machen und nicht nur für jede Action. Wie sich das gestaltet, habe ich allerdings keine Ahnung, dafür verstehe ich den Code noch zu wenig
