### ISSUE TITLE
Sigmoid: never used

### ISSUE THREAD

**Issue by manuel3108** [EasyDevCpp/SoftwareChallange#28]
Bei meinem letzten Commit cf8bc4b533c3b425fb7cc987ce707b158b9d06bd ist mir aufgefallen, dass der Sigmoid Teil nie richtig ausgeführt wird.

Trat bei mir bei jedem Spiel auf, nach dem Spielen lassen einfach mal in die Log schauen, ist dort die zweite Angabe in jeder Zeile. `false` bedeutet dass die Ai nicht gespielt hat, sondern unsere Parts

**Comment by EasyDevCpp** [comment]
Siehe #14 quality
