### ISSUE TITLE
ThirdPart: Es können nicht -10 Karotten aufgenommen werden

### ISSUE THREAD

**Issue by manuel3108** [EasyDevCpp/SoftwareChallange#30]
[30.zip](https://github.com/EasyDevCpp/SoftwareChallenge/files/1595168/30.zip)

**Comment by EasyDevCpp** [comment]
Connected to #19

**Comment by manuel3108** [comment]
Not sure. Here we just need a check, that we dont go under zero carrots.

Edit: Have a look at the replay
