### ISSUE TITLE
FirstPart: Vorwärtszug um 3 Felder nicht möglich

### ISSUE THREAD

**Issue by EasyDevCpp** [EasyDevCpp/SoftwareChallange#31]
[31.zip](https://github.com/EasyDevCpp/SoftwareChallenge/files/1595890/31.zip)
Quite unsure could be in your Part @manuel3108 or could be in Sigmoid.java...

The log.txt points out that the turn before that turn are all aimoves... But that doesn't mean the last one is also an aimove... 

Also fixing #29 was or is kind of ridiculous, because errors are technically not supposed to happen... I hoped that the gameState update a bit earlier would do the trick, but I am not sure about that...

So I will re-open #29 for now but I don't know how to fix... The problem must be deeper, if Sigmoid.java is really responsible for that one here...

**Comment by manuel3108** [comment]
I will have a look in the next days

**Comment by EasyDevCpp** [comment]
Obviously it's your part! We saw it in action today! But I guess getMostEfficientMove() will fix it up...
Also it should be prevented by our fallback routine... But it isn't working like it should be
