### ISSUE TITLE
Log displays the wrong Player all the time

### ISSUE THREAD

**Issue by EasyDevCpp** [EasyDevCpp/SoftwareChallange#33]
[33.zip](https://github.com/EasyDevCpp/SoftwareChallenge/files/1597073/33.zip)

**Comment by EasyDevCpp** [comment]
Or should it be: gameState.getOtherPlayer().getPlayerColor().name()... Is this intentional?

**Comment by EasyDevCpp** [comment]
@manuel3108 not sure cf34527c81682512517d3b19d6c5e09e02547f11 really fixed it... I thought that the onUpdate() isn't called again after an error, so the log has to be written before...

**Comment by EasyDevCpp** [comment]
Upps wrong issue...

**Comment by manuel3108** [comment]
No, this was an error. Thx for the fix
