### ISSUE TITLE
Too many turns => no end

### ISSUE THREAD

**Issue by manuel3108** [EasyDevCpp/SoftwareChallange#35]
If you play games against the RandomLogic, there is the problem that many of these games never end and we reach 60 turns.

We need to improve this.

**Comment by EasyDevCpp** [comment]
For me this is not true... ATM most games end around 45 turns with wins on both sides... Most often on our side... So maybe it's all about that quality value which actually causes the thirdpart atm to make no aimoves...

**Comment by EasyDevCpp** [comment]
I'm on it right now!
