### ISSUE TITLE
ThirdPart is mostly useless (<3)

### ISSUE THREAD

**Issue by EasyDevCpp** [EasyDevCpp/SoftwareChallange#8]
Part3 macht ungültige Züge!

**Comment by EasyDevCpp** [comment]
![issue 8](https://user-images.githubusercontent.com/29622401/31850383-3ba10b72-b651-11e7-9af6-d0482a302ac2.png)

**Comment by manuel3108** [comment]
Zeile 155 im ThirdPart muss durch `return m` ersetzt werden
