### ISSUE TITLE
order attribute is undefined

### ISSUE THREAD

**Issue by Blajous** [EasyDevCpp/SoftwareChallange#9]
Siehe Bild & Log
[order_undefined.txt](https://github.com/EasyDevCpp/SoftwareChallange/files/1430627/order_undefined.txt)
![image](https://user-images.githubusercontent.com/31953147/32223342-3ed883e4-be3d-11e7-8d0b-9d213de9834f.png)

**Comment by manuel3108** [comment]
Closing with 3c5e21b
